# based on https://github.com/hyperledger/aries-framework-javascript-ext/blob/main/.github/actions/setup-node/action.yml
name: Setup NodeJS
description: Setup NodeJS with caching
author: "timo@animo.id"

inputs:
  node-version:
    description: Select the nodejs version to use
    required: false
    default: "18.18.2"

runs:
  using: composite
  steps:
    - name: Add package manager
      shell: bash
      run: |
        corepack enable

    - uses: pnpm/action-setup@v4

    - name: Setup node v${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org/"
        cache: "pnpm"

    - name: Node Version
      shell: bash
      run: |
        node -v && pnpm -v
