version: '3.5'

services:
  animo-mediator:
    image: ghcr.io/animo/animo-mediator:${IMAGE_TAG}
    networks:
      - traefik
    deploy:
      labels:
        # Enable traefik so the container can be exposed to the outside world
        traefik.enable: 'true'

        # HTTP and WS communication
        traefik.http.routers.animo-mediator.rule: Host(`mediator.dev.animo.id`)
        traefik.http.routers.animo-mediator.entrypoints: web-secure
        traefik.http.routers.animo-mediator.tls.certresolver: zerossl
        traefik.http.routers.animo-mediator.service: animo-mediator-service
        traefik.http.services.animo-mediator-service.loadbalancer.server.port: 3000
    environment:
      AGENT_PORT: 3000
      AGENT_LABEL: Animo Mediator
      WALLET_ID: animo-mediator
      WALLET_KEY: ${WALLET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      AGENT_ENDPOINTS: 'https://mediator.dev.animo.id,wss://mediator.dev.animo.id'
      INVITATION_URL: https://mediator.dev.animo.id/invite
      LOG_LEVEL: 2
    ports:
      - '3000'

networks:
  traefik:
    external: true
    name: traefik
