version: "3.9"

networks:
  local_credo_mediator_network:
    name: local_credo_mediator_network
volumes:
  postgres-data:


services:
  postgres:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local_credo_mediator_network

  mediator:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    working_dir: /work
    volumes:
      - ../:/work
      - /work/node_modules
    ports:
      - "3110:3110"
    tty: true
    networks:
      - local_credo_mediator_network
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=postgres
