## Common Values
namespace: mediator


## Deployment Values
deployment_name: mediator
replicas: 1

image: 
  name: ghcr.io/openwallet-foundation/didcomm-mediator-credo
  tag: latest

container:
  name: mediator
  port: 3000
  imagePullPolicy: Always

environment:
  AGENT_PORT: 3000
  AGENT_NAME: Mediator
  WALLET_NAME: mediator
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
  POSTGRES_ADMIN_PASSWORD: {}
  AGENT_ENDPOINTS: {}
  LOG_LEVEL: 2

resources:
  requests:
    memory: 256Mi
    cpu: 20m
  limits:
    memory: 256Mi
    cpu: 100m

## Service Values
service_name: mediator


## Ingress Values
ingress_name: mediator_ingress
cluster_issuer_name: nginx
host_name: example.com
certificate_secret_name: my-cert
