name: Deploy Stack

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the image'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Stack
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Template Stack
        uses: ./.github/actions/deploy
        env:
          WALLET_KEY: ${{ secrets.WALLET_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_ADMIN_USER: ${{ secrets.POSTGRES_ADMIN_USER }}
          POSTGRES_ADMIN_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          IMAGE_TAG: ${{ inputs.tag }}
        with:
          envs: WALLET_KEY,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_HOST,POSTGRES_ADMIN_USER,POSTGRES_ADMIN_PASSWORD,IMAGE_TAG
          stack-name: animo-afj-mediator
          stack-file: ./docker-compose-animo-mediator.yml
          private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
