name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
  workflow_run:
    workflows: [Quality]
    branches: [main]
    types:
      - completed
env:
  REGISTRY: ghcr.io

jobs:
  release-image:
    name: Publish Image
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build mediator image
        uses: ./.github/actions/docker-build
        with:
          registry: ${{ env.REGISTRY }}
          image_name: "${{ github.repository }}/mediator"
          context: ./apps/mediator
          dockerfile: "Dockerfile"
          docker_user: ${{ github.actor }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
