apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment_name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{ .Values.container.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 45
          timeoutSeconds: 3
        env:
        - name: AGENT_PORT
          value: {{ .Values.environment.AGENT_PORT }}
        - name: AGENT_NAME
          value: {{ .Values.environment.AGENT_NAME }}
        - name: WALLET_NAME
          value: {{ .Values.environment.WALLET_NAME }}                     
        - name: WALLET_KEY
          envFrom:
            - secretRef:
                name: {{ include "mediator-agent.fullname" . }}-creds
        - name: POSTGRES_USER
          value: {{ .Values.environment.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: {{ include "mediator-agent.fullname" . }}-postgresql-creds
        - name: POSTGRES_HOST
          value: {{ .Values.environment.POSTGRES_HOST }}
        - name: POSTGRES_ADMIN_USER
          value: {{ .Values.environment.POSTGRES_ADMIN_USER }}
        - name: POSTGRES_ADMIN_PASSWORD
          value: {{ .Values.environment.POSTGRES_ADMIN_PASSWORD }}
        - name: AGENT_ENDPOINTS
          value: {{ .Values.environment.AGENT_ENDPOINTS }}
        - name: LOG_LEVEL
          value: {{ .Values.environment.LOG_LEVEL }}
      volumeMounts:
        - name: cache-volume
          mountPath: /.cache
      
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 1Gi   
